# Generated by Django 5.0.4 on 2024-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerlike',
            name='status',
            field=models.CharField(choices=[('l', 'Like'), ('d', 'Dislike'), ('n', 'Not liked')], default='d', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionlike',
            name='status',
            field=models.CharField(choices=[('l', 'Like'), ('d', 'Dislike'), ('n', 'Not liked')], default='d', max_length=10),
        ),
    ]
