# Generated by Django 5.0.4 on 2024-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_alter_answerlike_status_alter_questionlike_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='img/avatar.png', null=True, upload_to=''),
        ),
    ]
